## Statistical Computation using NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [6]:
np.min(a)

0

In [7]:
print(np.min(a,axis=0))

[1 2 2 0]


In [8]:
b = np.array([1,2,3,4,5])
print(np.mean(b))

3.0


In [10]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [11]:
print(np.std(c))

1.854723699099141


In [12]:
print(np.var(c))

3.4400000000000004
