## NumPy Random Module

In [2]:
import numpy as np

In [4]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[5 4 6 9 1 3 2 8 7 0]


In [11]:
b = np.random.randn(2,3)
print(b)

[[ 0.13665051  1.26054017 -1.01540057]
 [-0.02339557  1.44737877 -1.84008061]]


In [14]:
c = np.random.randint(5,10,3)
print(c)

[7 8 7]


In [17]:
d = np.random.choice([1,4,56,23])
print(d)

1
