## NumPy

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [8]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [9]:
c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [11]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
e = np.random.random((2,3))
print(e)

[[0.41565036 0.84270015 0.040079  ]
 [0.07790387 0.59711781 0.63263307]]


In [16]:
print(e[:,1])

[0.84270015 0.59711781]


In [18]:
e[1,1:3] = 1
print(e)

[[0.41565036 0.84270015 0.040079  ]
 [0.07790387 1.         1.        ]]


In [20]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
z[1,:] = 5
print(z)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [22]:
z[:,-1] = 7
print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [23]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.dot(a,b))

30


In [24]:
b=b**2
print(b)
print(a)

[ 1  4  9 16]
[1 2 3 4]


In [30]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])